<?php

namespace AppBundle\Repository;

/**
 * OnderwijsperiodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnderwijsperiodeRepository extends \Doctrine\ORM\EntityRepository
{
}
